platform :ios, '6.0'
pod 'PrettyKit', '~>0.2.0'
pod 'BlocksKit'
pod 'KKPasscodeLock', '~> 0.1.5'
pod 'GoogleAnalytics-iOS-SDK'
pod 'ObjectiveSugar'
pod 'MHPrettyDate'
pod 'AJNotificationView', '~> 0.0.1'
pod 'SVProgressHUD'
pod 'ActionSheetPicker2'
pod 'Reachability'